### ISSUE TITLE
Not able to program/download

### ISSUE THREAD

**Issue by Rednas83** [david9991/plcc-plugin#2]
Do I need more software?
wss://le-132.g.pocograph.com/ // This is not working on my laptop

Or perhaps specific hardware to be able to download?

Is it possible to download to your own laptop as well?

Can you also develop locally or does it require cloud?

**Version**
vscode 1.68.1 (latest)
dotnet-sdk-6.0.301-win-x64 (latest)

**Comment by david9991** [comment]
Download means downloading to the PLC device, currently we only support a few models of HCFA PLC devices, but they have not been released yet. I will update this ticket if there is any news.

**Comment by Mztea928** [comment]
Lol
