### ISSUE TITLE
Not able to change variables in graph

### ISSUE THREAD

**Issue by Rednas83** [david9991/plcc-plugin#3]
I am able to write ladder, but I am not able to edit the variables.
![image](https://user-images.githubusercontent.com/25219229/174431853-892864fc-9252-472d-9782-f6c561b5e6c9.png)

How can I do this?

**Version**
vscode 1.68.1 (latest)
dotnet-sdk-6.0.301-win-x64 (latest)

**Comment by david9991** [comment]
Sorry, this project is still under heavy development. Ladder Diagram is still in very early version and is not currently available, but will be available soon in the next version. I will update the status of this ticket when it works.

**Comment by david9991** [comment]
It works in the latest version.
