### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by caixiao7** [david9991/plcc-plugin#4]
你好，可不可以分享下思路这个插件是怎么实现的，我现在也想尝试实现梯形图的编辑器，通过glsp吗

**Comment by david9991** [comment]
glsp 是 go 语言 language server protocol 的库，和梯形图没有关系。我们的梯形图没有使用第三方库，完全手工实现，通过实现一个简单的 DAG 并遍历这个图计算布局，然后做成 Display List（类似于 GPU 中的 Command List），再通过前端渲染成 SVG 实现的，没有什么特别的实现。

**Comment by david9991** [comment]
你指的 glsp 是 eclipse glsp ？我们没有用过这个，不太了解。
